# Generated by Django 3.1.5 on 2021-01-19 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('status', models.CharField(blank=True, max_length=140, null=True, verbose_name='Статус')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Информация о себе')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Профиль пользователя')),
            ],
        ),
    ]
