# Generated by Django 3.1.5 on 2021-01-19 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Заголовок')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заметки')),
                ('text', models.TextField(verbose_name='Текст заметки')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.users', verbose_name='Автор заметки')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'db_table': 'notes',
                'ordering': ['-date'],
            },
        ),
    ]
